name: Deploy to Server

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            export PATH="/home/vactor/.nvm/versions/node/v24.15.0/bin:$PATH"
            cd ~/jcore/
            git pull origin main
            npm install
            npm run build
            pm2 restart "jcore"
            pm2 logs --lines 20 --nostream
